Traceback (most recent call last):
  File "/Users/mac/anaconda3/lib/python3.11/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/mac/anaconda3/lib/python3.11/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/anaconda3/lib/python3.11/site-packages/jupyter_core/utils/__init__.py", line 173, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/anaconda3/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/mac/anaconda3/lib/python3.11/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/Users/mac/anaconda3/lib/python3.11/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/mac/anaconda3/lib/python3.11/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
stocksymb='300339'
periods=['daily','weekly','monthly']
stockDict=plotDcStocks(stocksymb,periods)
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mTimeoutError[0m                              Traceback (most recent call last)
File [0;32m~/anaconda3/lib/python3.11/site-packages/urllib3/connectionpool.py:776[0m, in [0;36mHTTPConnectionPool.urlopen[0;34m(self, method, url, body, headers, retries, redirect, assert_same_host, timeout, pool_timeout, release_conn, chunked, body_pos, preload_content, decode_content, **response_kw)[0m
[1;32m    775[0m [38;5;28;01mtry[39;00m:
[0;32m--> 776[0m     [38;5;28mself[39m[38;5;241m.[39m_prepare_proxy(conn)
[1;32m    777[0m [38;5;28;01mexcept[39;00m (BaseSSLError, [38;5;167;01mOSError[39;00m, SocketTimeout) [38;5;28;01mas[39;00m e:

File [0;32m~/anaconda3/lib/python3.11/site-packages/urllib3/connectionpool.py:1041[0m, in [0;36mHTTPSConnectionPool._prepare_proxy[0;34m(self, conn)[0m
[1;32m   1035[0m conn[38;5;241m.[39mset_tunnel(
[1;32m   1036[0m     scheme[38;5;241m=[39mtunnel_scheme,
[1;32m   1037[0m     host[38;5;241m=[39m[38;5;28mself[39m[38;5;241m.[39m_tunnel_host,
[1;32m   1038[0m     port[38;5;241m=[39m[38;5;28mself[39m[38;5;241m.[39mport,
[1;32m   1039[0m     headers[38;5;241m=[39m[38;5;28mself[39m[38;5;241m.[39mproxy_headers,
[1;32m   1040[0m )
[0;32m-> 1041[0m conn[38;5;241m.[39mconnect()

File [0;32m~/anaconda3/lib/python3.11/site-packages/urllib3/connection.py:635[0m, in [0;36mHTTPSConnection.connect[0;34m(self)[0m
[1;32m    627[0m     warnings[38;5;241m.[39mwarn(
[1;32m    628[0m         (
[1;32m    629[0m             [38;5;124mf[39m[38;5;124m"[39m[38;5;124mSystem time is way off (before [39m[38;5;132;01m{[39;00mRECENT_DATE[38;5;132;01m}[39;00m[38;5;124m). This will probably [39m[38;5;124m"[39m
[0;32m   (...)[0m
[1;32m    632[0m         SystemTimeWarning,
[1;32m    633[0m     )
[0;32m--> 635[0m sock_and_verified [38;5;241m=[39m _ssl_wrap_socket_and_match_hostname(
[1;32m    636[0m     sock[38;5;241m=[39msock,
[1;32m    637[0m     cert_reqs[38;5;241m=[39m[38;5;28mself[39m[38;5;241m.[39mcert_reqs,
[1;32m    638[0m     ssl_version[38;5;241m=[39m[38;5;28mself[39m[38;5;241m.[39mssl_version,
[1;32m    639[0m     ssl_minimum_version[38;5;241m=[39m[38;5;28mself[39m[38;5;241m.[39mssl_minimum_version,
[1;32m    640[0m     ssl_maximum_version[38;5;241m=[39m[38;5;28mself[39m[38;5;241m.[39mssl_maximum_version,
[1;32m    641[0m     ca_certs[38;5;241m=[39m[38;5;28mself[39m[38;5;241m.[39mca_certs,
[1;32m    642[0m     ca_cert_dir[38;5;241m=[39m[38;5;28mself[39m[38;5;241m.[39mca_cert_dir,
[1;32m    643[0m     ca_cert_data[38;5;241m=[39m[38;5;28mself[39m[38;5;241m.[39mca_cert_data,
[1;32m    644[0m     cert_file[38;5;241m=[39m[38;5;28mself[39m[38;5;241m.[39mcert_file,
[1;32m    645[0m     key_file[38;5;241m=[39m[38;5;28mself[39m[38;5;241m.[39mkey_file,
[1;32m    646[0m     key_password[38;5;241m=[39m[38;5;28mself[39m[38;5;241m.[39mkey_password,
[1;32m    647[0m     server_hostname[38;5;241m=[39mserver_hostname,
[1;32m    648[0m     ssl_context[38;5;241m=[39m[38;5;28mself[39m[38;5;241m.[39mssl_context,
[1;32m    649[0m     tls_in_tls[38;5;241m=[39mtls_in_tls,
[1;32m    650[0m     assert_hostname[38;5;241m=[39m[38;5;28mself[39m[38;5;241m.[39massert_hostname,
[1;32m    651[0m     assert_fingerprint[38;5;241m=[39m[38;5;28mself[39m[38;5;241m.[39massert_fingerprint,
[1;32m    652[0m )
[1;32m    653[0m [38;5;28mself[39m[38;5;241m.[39msock [38;5;241m=[39m sock_and_verified[38;5;241m.[39msocket

File [0;32m~/anaconda3/lib/python3.11/site-packages/urllib3/connection.py:776[0m, in [0;36m_ssl_wrap_socket_and_match_hostname[0;34m(sock, cert_reqs, ssl_version, ssl_minimum_version, ssl_maximum_version, cert_file, key_file, key_password, ca_certs, ca_cert_dir, ca_cert_data, assert_hostname, assert_fingerprint, server_hostname, ssl_context, tls_in_tls)[0m
[1;32m    774[0m         server_hostname [38;5;241m=[39m normalized
[0;32m--> 776[0m ssl_sock [38;5;241m=[39m ssl_wrap_socket(
[1;32m    777[0m     sock[38;5;241m=[39msock,
[1;32m    778[0m     keyfile[38;5;241m=[39mkey_file,
[1;32m    779[0m     certfile[38;5;241m=[39mcert_file,
[1;32m    780[0m     key_password[38;5;241m=[39mkey_password,
[1;32m    781[0m     ca_certs[38;5;241m=[39mca_certs,
[1;32m    782[0m     ca_cert_dir[38;5;241m=[39mca_cert_dir,
[1;32m    783[0m     ca_cert_data[38;5;241m=[39mca_cert_data,
[1;32m    784[0m     server_hostname[38;5;241m=[39mserver_hostname,
[1;32m    785[0m     ssl_context[38;5;241m=[39mcontext,
[1;32m    786[0m     tls_in_tls[38;5;241m=[39mtls_in_tls,
[1;32m    787[0m )
[1;32m    789[0m [38;5;28;01mtry[39;00m:

File [0;32m~/anaconda3/lib/python3.11/site-packages/urllib3/util/ssl_.py:466[0m, in [0;36mssl_wrap_socket[0;34m(sock, keyfile, certfile, cert_reqs, ca_certs, server_hostname, ssl_version, ciphers, ssl_context, ca_cert_dir, key_password, ca_cert_data, tls_in_tls)[0m
[1;32m    464[0m     [38;5;28;01mpass[39;00m
[0;32m--> 466[0m ssl_sock [38;5;241m=[39m _ssl_wrap_socket_impl(sock, context, tls_in_tls, server_hostname)
[1;32m    467[0m [38;5;28;01mreturn[39;00m ssl_sock

File [0;32m~/anaconda3/lib/python3.11/site-packages/urllib3/util/ssl_.py:510[0m, in [0;36m_ssl_wrap_socket_impl[0;34m(sock, ssl_context, tls_in_tls, server_hostname)[0m
[1;32m    508[0m     [38;5;28;01mreturn[39;00m SSLTransport(sock, ssl_context, server_hostname)
[0;32m--> 510[0m [38;5;28;01mreturn[39;00m ssl_context[38;5;241m.[39mwrap_socket(sock, server_hostname[38;5;241m=[39mserver_hostname)

File [0;32m~/anaconda3/lib/python3.11/ssl.py:517[0m, in [0;36mSSLContext.wrap_socket[0;34m(self, sock, server_side, do_handshake_on_connect, suppress_ragged_eofs, server_hostname, session)[0m
[1;32m    511[0m [38;5;28;01mdef[39;00m [38;5;21mwrap_socket[39m([38;5;28mself[39m, sock, server_side[38;5;241m=[39m[38;5;28;01mFalse[39;00m,
[1;32m    512[0m                 do_handshake_on_connect[38;5;241m=[39m[38;5;28;01mTrue[39;00m,
[1;32m    513[0m                 suppress_ragged_eofs[38;5;241m=[39m[38;5;28;01mTrue[39;00m,
[1;32m    514[0m                 server_hostname[38;5;241m=[39m[38;5;28;01mNone[39;00m, session[38;5;241m=[39m[38;5;28;01mNone[39;00m):
[1;32m    515[0m     [38;5;66;03m# SSLSocket class handles server_hostname encoding before it calls[39;00m
[1;32m    516[0m     [38;5;66;03m# ctx._wrap_socket()[39;00m
[0;32m--> 517[0m     [38;5;28;01mreturn[39;00m [38;5;28mself[39m[38;5;241m.[39msslsocket_class[38;5;241m.[39m_create(
[1;32m    518[0m         sock[38;5;241m=[39msock,
[1;32m    519[0m         server_side[38;5;241m=[39mserver_side,
[1;32m    520[0m         do_handshake_on_connect[38;5;241m=[39mdo_handshake_on_connect,
[1;32m    521[0m         suppress_ragged_eofs[38;5;241m=[39msuppress_ragged_eofs,
[1;32m    522[0m         server_hostname[38;5;241m=[39mserver_hostname,
[1;32m    523[0m         context[38;5;241m=[39m[38;5;28mself[39m,
[1;32m    524[0m         session[38;5;241m=[39msession
[1;32m    525[0m     )

File [0;32m~/anaconda3/lib/python3.11/ssl.py:1108[0m, in [0;36mSSLSocket._create[0;34m(cls, sock, server_side, do_handshake_on_connect, suppress_ragged_eofs, server_hostname, context, session)[0m
[1;32m   1107[0m             [38;5;28;01mraise[39;00m [38;5;167;01mValueError[39;00m([38;5;124m"[39m[38;5;124mdo_handshake_on_connect should not be specified for non-blocking sockets[39m[38;5;124m"[39m)
[0;32m-> 1108[0m         [38;5;28mself[39m[38;5;241m.[39mdo_handshake()
[1;32m   1109[0m [38;5;28;01mexcept[39;00m ([38;5;167;01mOSError[39;00m, [38;5;167;01mValueError[39;00m):

File [0;32m~/anaconda3/lib/python3.11/ssl.py:1379[0m, in [0;36mSSLSocket.do_handshake[0;34m(self, block)[0m
[1;32m   1378[0m         [38;5;28mself[39m[38;5;241m.[39msettimeout([38;5;28;01mNone[39;00m)
[0;32m-> 1379[0m     [38;5;28mself[39m[38;5;241m.[39m_sslobj[38;5;241m.[39mdo_handshake()
[1;32m   1380[0m [38;5;28;01mfinally[39;00m:

[0;31mTimeoutError[0m: _ssl.c:989: The handshake operation timed out

The above exception was the direct cause of the following exception:

[0;31mReadTimeoutError[0m                          Traceback (most recent call last)
File [0;32m~/anaconda3/lib/python3.11/site-packages/requests/adapters.py:486[0m, in [0;36mHTTPAdapter.send[0;34m(self, request, stream, timeout, verify, cert, proxies)[0m
[1;32m    485[0m [38;5;28;01mtry[39;00m:
[0;32m--> 486[0m     resp [38;5;241m=[39m conn[38;5;241m.[39murlopen(
[1;32m    487[0m         method[38;5;241m=[39mrequest[38;5;241m.[39mmethod,
[1;32m    488[0m         url[38;5;241m=[39murl,
[1;32m    489[0m         body[38;5;241m=[39mrequest[38;5;241m.[39mbody,
[1;32m    490[0m         headers[38;5;241m=[39mrequest[38;5;241m.[39mheaders,
[1;32m    491[0m         redirect[38;5;241m=[39m[38;5;28;01mFalse[39;00m,
[1;32m    492[0m         assert_same_host[38;5;241m=[39m[38;5;28;01mFalse[39;00m,
[1;32m    493[0m         preload_content[38;5;241m=[39m[38;5;28;01mFalse[39;00m,
[1;32m    494[0m         decode_content[38;5;241m=[39m[38;5;28;01mFalse[39;00m,
[1;32m    495[0m         retries[38;5;241m=[39m[38;5;28mself[39m[38;5;241m.[39mmax_retries,
[1;32m    496[0m         timeout[38;5;241m=[39mtimeout,
[1;32m    497[0m         chunked[38;5;241m=[39mchunked,
[1;32m    498[0m     )
[1;32m    500[0m [38;5;28;01mexcept[39;00m (ProtocolError, [38;5;167;01mOSError[39;00m) [38;5;28;01mas[39;00m err:

File [0;32m~/anaconda3/lib/python3.11/site-packages/urllib3/connectionpool.py:844[0m, in [0;36mHTTPConnectionPool.urlopen[0;34m(self, method, url, body, headers, retries, redirect, assert_same_host, timeout, pool_timeout, release_conn, chunked, body_pos, preload_content, decode_content, **response_kw)[0m
[1;32m    842[0m     new_e [38;5;241m=[39m ProtocolError([38;5;124m"[39m[38;5;124mConnection aborted.[39m[38;5;124m"[39m, new_e)
[0;32m--> 844[0m retries [38;5;241m=[39m retries[38;5;241m.[39mincrement(
[1;32m    845[0m     method, url, error[38;5;241m=[39mnew_e, _pool[38;5;241m=[39m[38;5;28mself[39m, _stacktrace[38;5;241m=[39msys[38;5;241m.[39mexc_info()[[38;5;241m2[39m]
[1;32m    846[0m )
[1;32m    847[0m retries[38;5;241m.[39msleep()

File [0;32m~/anaconda3/lib/python3.11/site-packages/urllib3/util/retry.py:470[0m, in [0;36mRetry.increment[0;34m(self, method, url, response, error, _pool, _stacktrace)[0m
[1;32m    469[0m [38;5;28;01mif[39;00m read [38;5;129;01mis[39;00m [38;5;28;01mFalse[39;00m [38;5;129;01mor[39;00m method [38;5;129;01mis[39;00m [38;5;28;01mNone[39;00m [38;5;129;01mor[39;00m [38;5;129;01mnot[39;00m [38;5;28mself[39m[38;5;241m.[39m_is_method_retryable(method):
[0;32m--> 470[0m     [38;5;28;01mraise[39;00m reraise([38;5;28mtype[39m(error), error, _stacktrace)
[1;32m    471[0m [38;5;28;01melif[39;00m read [38;5;129;01mis[39;00m [38;5;129;01mnot[39;00m [38;5;28;01mNone[39;00m:

File [0;32m~/anaconda3/lib/python3.11/site-packages/urllib3/util/util.py:39[0m, in [0;36mreraise[0;34m(tp, value, tb)[0m
[1;32m     38[0m         [38;5;28;01mraise[39;00m value[38;5;241m.[39mwith_traceback(tb)
[0;32m---> 39[0m     [38;5;28;01mraise[39;00m value
[1;32m     40[0m [38;5;28;01mfinally[39;00m:

File [0;32m~/anaconda3/lib/python3.11/site-packages/urllib3/connectionpool.py:778[0m, in [0;36mHTTPConnectionPool.urlopen[0;34m(self, method, url, body, headers, retries, redirect, assert_same_host, timeout, pool_timeout, release_conn, chunked, body_pos, preload_content, decode_content, **response_kw)[0m
[1;32m    777[0m [38;5;28;01mexcept[39;00m (BaseSSLError, [38;5;167;01mOSError[39;00m, SocketTimeout) [38;5;28;01mas[39;00m e:
[0;32m--> 778[0m     [38;5;28mself[39m[38;5;241m.[39m_raise_timeout(
[1;32m    779[0m         err[38;5;241m=[39me, url[38;5;241m=[39m[38;5;28mself[39m[38;5;241m.[39mproxy[38;5;241m.[39murl, timeout_value[38;5;241m=[39mconn[38;5;241m.[39mtimeout
[1;32m    780[0m     )
[1;32m    781[0m     [38;5;28;01mraise[39;00m

File [0;32m~/anaconda3/lib/python3.11/site-packages/urllib3/connectionpool.py:370[0m, in [0;36mHTTPConnectionPool._raise_timeout[0;34m(self, err, url, timeout_value)[0m
[1;32m    369[0m [38;5;28;01mif[39;00m [38;5;28misinstance[39m(err, SocketTimeout):
[0;32m--> 370[0m     [38;5;28;01mraise[39;00m ReadTimeoutError(
[1;32m    371[0m         [38;5;28mself[39m, url, [38;5;124mf[39m[38;5;124m"[39m[38;5;124mRead timed out. (read timeout=[39m[38;5;132;01m{[39;00mtimeout_value[38;5;132;01m}[39;00m[38;5;124m)[39m[38;5;124m"[39m
[1;32m    372[0m     ) [38;5;28;01mfrom[39;00m [38;5;21;01merr[39;00m
[1;32m    374[0m [38;5;66;03m# See the above comment about EAGAIN in Python 3.[39;00m

[0;31mReadTimeoutError[0m: HTTPSConnectionPool(host='80.push2delay.eastmoney.com', port=443): Read timed out. (read timeout=15)

During handling of the above exception, another exception occurred:

[0;31mReadTimeout[0m                               Traceback (most recent call last)
Cell [0;32mIn[28], line 3[0m
[1;32m      1[0m stocksymb[38;5;241m=[39m[38;5;124m'[39m[38;5;124m300339[39m[38;5;124m'[39m
[1;32m      2[0m periods[38;5;241m=[39m[[38;5;124m'[39m[38;5;124mdaily[39m[38;5;124m'[39m,[38;5;124m'[39m[38;5;124mweekly[39m[38;5;124m'[39m,[38;5;124m'[39m[38;5;124mmonthly[39m[38;5;124m'[39m]
[0;32m----> 3[0m stockDict[38;5;241m=[39mplotDcStocks(stocksymb,periods)

Cell [0;32mIn[27], line 4[0m, in [0;36mplotDcStocks[0;34m(stocksymb, periods)[0m
[1;32m      2[0m stockDict[38;5;241m=[39m{}
[1;32m      3[0m [38;5;28;01mfor[39;00m p [38;5;129;01min[39;00m periods:
[0;32m----> 4[0m     stockdf [38;5;241m=[39m ak[38;5;241m.[39mstock_zh_a_hist(symbol[38;5;241m=[39mstocksymb,period[38;5;241m=[39mp)
[1;32m      5[0m     stocknamedf[38;5;241m=[39mak[38;5;241m.[39mstock_individual_info_em(symbol[38;5;241m=[39mstocksymb)
[1;32m      6[0m     stockname[38;5;241m=[39mstocknamedf[38;5;241m.[39mloc[stocknamedf[[38;5;124m'[39m[38;5;124mitem[39m[38;5;124m'[39m][38;5;241m==[39m[38;5;124m'[39m[38;5;124m股票简称[39m[38;5;124m'[39m,[38;5;124m'[39m[38;5;124mvalue[39m[38;5;124m'[39m][[38;5;241m1[39m]

File [0;32m~/anaconda3/lib/python3.11/site-packages/akshare/stock_feature/stock_hist_em.py:1041[0m, in [0;36mstock_zh_a_hist[0;34m(symbol, period, start_date, end_date, adjust, timeout)[0m
[1;32m   1015[0m [38;5;28;01mdef[39;00m [38;5;21mstock_zh_a_hist[39m(
[1;32m   1016[0m     symbol: [38;5;28mstr[39m [38;5;241m=[39m [38;5;124m"[39m[38;5;124m000001[39m[38;5;124m"[39m,
[1;32m   1017[0m     period: [38;5;28mstr[39m [38;5;241m=[39m [38;5;124m"[39m[38;5;124mdaily[39m[38;5;124m"[39m,
[0;32m   (...)[0m
[1;32m   1021[0m     timeout: [38;5;28mfloat[39m [38;5;241m=[39m [38;5;28;01mNone[39;00m,
[1;32m   1022[0m ) [38;5;241m-[39m[38;5;241m>[39m pd[38;5;241m.[39mDataFrame:
[1;32m   1023[0m [38;5;250m    [39m[38;5;124;03m"""[39;00m
[1;32m   1024[0m [38;5;124;03m    东方财富网-行情首页-沪深京 A 股-每日行情[39;00m
[1;32m   1025[0m [38;5;124;03m    https://quote.eastmoney.com/concept/sh603777.html?from=classic[39;00m
[0;32m   (...)[0m
[1;32m   1039[0m [38;5;124;03m    :rtype: pandas.DataFrame[39;00m
[1;32m   1040[0m [38;5;124;03m    """[39;00m
[0;32m-> 1041[0m     code_id_dict [38;5;241m=[39m code_id_map_em()
[1;32m   1042[0m     adjust_dict [38;5;241m=[39m {[38;5;124m"[39m[38;5;124mqfq[39m[38;5;124m"[39m: [38;5;124m"[39m[38;5;124m1[39m[38;5;124m"[39m, [38;5;124m"[39m[38;5;124mhfq[39m[38;5;124m"[39m: [38;5;124m"[39m[38;5;124m2[39m[38;5;124m"[39m, [38;5;124m"[39m[38;5;124m"[39m: [38;5;124m"[39m[38;5;124m0[39m[38;5;124m"[39m}
[1;32m   1043[0m     period_dict [38;5;241m=[39m {[38;5;124m"[39m[38;5;124mdaily[39m[38;5;124m"[39m: [38;5;124m"[39m[38;5;124m101[39m[38;5;124m"[39m, [38;5;124m"[39m[38;5;124mweekly[39m[38;5;124m"[39m: [38;5;124m"[39m[38;5;124m102[39m[38;5;124m"[39m, [38;5;124m"[39m[38;5;124mmonthly[39m[38;5;124m"[39m: [38;5;124m"[39m[38;5;124m103[39m[38;5;124m"[39m}

File [0;32m~/anaconda3/lib/python3.11/site-packages/akshare/stock_feature/stock_hist_em.py:964[0m, in [0;36mcode_id_map_em[0;34m()[0m
[1;32m    950[0m url [38;5;241m=[39m [38;5;124m"[39m[38;5;124mhttps://80.push2.eastmoney.com/api/qt/clist/get[39m[38;5;124m"[39m
[1;32m    951[0m params [38;5;241m=[39m {
[1;32m    952[0m     [38;5;124m"[39m[38;5;124mpn[39m[38;5;124m"[39m: [38;5;124m"[39m[38;5;124m1[39m[38;5;124m"[39m,
[1;32m    953[0m     [38;5;124m"[39m[38;5;124mpz[39m[38;5;124m"[39m: [38;5;124m"[39m[38;5;124m50000[39m[38;5;124m"[39m,
[0;32m   (...)[0m
[1;32m    962[0m     [38;5;124m"[39m[38;5;124m_[39m[38;5;124m"[39m: [38;5;124m"[39m[38;5;124m1623833739532[39m[38;5;124m"[39m,
[1;32m    963[0m }
[0;32m--> 964[0m r [38;5;241m=[39m requests[38;5;241m.[39mget(url, timeout[38;5;241m=[39m[38;5;241m15[39m, params[38;5;241m=[39mparams)
[1;32m    965[0m data_json [38;5;241m=[39m r[38;5;241m.[39mjson()
[1;32m    966[0m [38;5;28;01mif[39;00m [38;5;129;01mnot[39;00m data_json[[38;5;124m"[39m[38;5;124mdata[39m[38;5;124m"[39m][[38;5;124m"[39m[38;5;124mdiff[39m[38;5;124m"[39m]:

File [0;32m~/anaconda3/lib/python3.11/site-packages/requests/api.py:73[0m, in [0;36mget[0;34m(url, params, **kwargs)[0m
[1;32m     62[0m [38;5;28;01mdef[39;00m [38;5;21mget[39m(url, params[38;5;241m=[39m[38;5;28;01mNone[39;00m, [38;5;241m*[39m[38;5;241m*[39mkwargs):
[1;32m     63[0m [38;5;250m    [39m[38;5;124mr[39m[38;5;124;03m"""Sends a GET request.[39;00m
[1;32m     64[0m 
[1;32m     65[0m [38;5;124;03m    :param url: URL for the new :class:`Request` object.[39;00m
[0;32m   (...)[0m
[1;32m     70[0m [38;5;124;03m    :rtype: requests.Response[39;00m
[1;32m     71[0m [38;5;124;03m    """[39;00m
[0;32m---> 73[0m     [38;5;28;01mreturn[39;00m request([38;5;124m"[39m[38;5;124mget[39m[38;5;124m"[39m, url, params[38;5;241m=[39mparams, [38;5;241m*[39m[38;5;241m*[39mkwargs)

File [0;32m~/anaconda3/lib/python3.11/site-packages/requests/api.py:59[0m, in [0;36mrequest[0;34m(method, url, **kwargs)[0m
[1;32m     55[0m [38;5;66;03m# By using the 'with' statement we are sure the session is closed, thus we[39;00m
[1;32m     56[0m [38;5;66;03m# avoid leaving sockets open which can trigger a ResourceWarning in some[39;00m
[1;32m     57[0m [38;5;66;03m# cases, and look like a memory leak in others.[39;00m
[1;32m     58[0m [38;5;28;01mwith[39;00m sessions[38;5;241m.[39mSession() [38;5;28;01mas[39;00m session:
[0;32m---> 59[0m     [38;5;28;01mreturn[39;00m session[38;5;241m.[39mrequest(method[38;5;241m=[39mmethod, url[38;5;241m=[39murl, [38;5;241m*[39m[38;5;241m*[39mkwargs)

File [0;32m~/anaconda3/lib/python3.11/site-packages/requests/sessions.py:589[0m, in [0;36mSession.request[0;34m(self, method, url, params, data, headers, cookies, files, auth, timeout, allow_redirects, proxies, hooks, stream, verify, cert, json)[0m
[1;32m    584[0m send_kwargs [38;5;241m=[39m {
[1;32m    585[0m     [38;5;124m"[39m[38;5;124mtimeout[39m[38;5;124m"[39m: timeout,
[1;32m    586[0m     [38;5;124m"[39m[38;5;124mallow_redirects[39m[38;5;124m"[39m: allow_redirects,
[1;32m    587[0m }
[1;32m    588[0m send_kwargs[38;5;241m.[39mupdate(settings)
[0;32m--> 589[0m resp [38;5;241m=[39m [38;5;28mself[39m[38;5;241m.[39msend(prep, [38;5;241m*[39m[38;5;241m*[39msend_kwargs)
[1;32m    591[0m [38;5;28;01mreturn[39;00m resp

File [0;32m~/anaconda3/lib/python3.11/site-packages/requests/sessions.py:725[0m, in [0;36mSession.send[0;34m(self, request, **kwargs)[0m
[1;32m    722[0m [38;5;28;01mif[39;00m allow_redirects:
[1;32m    723[0m     [38;5;66;03m# Redirect resolving generator.[39;00m
[1;32m    724[0m     gen [38;5;241m=[39m [38;5;28mself[39m[38;5;241m.[39mresolve_redirects(r, request, [38;5;241m*[39m[38;5;241m*[39mkwargs)
[0;32m--> 725[0m     history [38;5;241m=[39m [resp [38;5;28;01mfor[39;00m resp [38;5;129;01min[39;00m gen]
[1;32m    726[0m [38;5;28;01melse[39;00m:
[1;32m    727[0m     history [38;5;241m=[39m []

File [0;32m~/anaconda3/lib/python3.11/site-packages/requests/sessions.py:725[0m, in [0;36m<listcomp>[0;34m(.0)[0m
[1;32m    722[0m [38;5;28;01mif[39;00m allow_redirects:
[1;32m    723[0m     [38;5;66;03m# Redirect resolving generator.[39;00m
[1;32m    724[0m     gen [38;5;241m=[39m [38;5;28mself[39m[38;5;241m.[39mresolve_redirects(r, request, [38;5;241m*[39m[38;5;241m*[39mkwargs)
[0;32m--> 725[0m     history [38;5;241m=[39m [resp [38;5;28;01mfor[39;00m resp [38;5;129;01min[39;00m gen]
[1;32m    726[0m [38;5;28;01melse[39;00m:
[1;32m    727[0m     history [38;5;241m=[39m []

File [0;32m~/anaconda3/lib/python3.11/site-packages/requests/sessions.py:266[0m, in [0;36mSessionRedirectMixin.resolve_redirects[0;34m(self, resp, req, stream, timeout, verify, cert, proxies, yield_requests, **adapter_kwargs)[0m
[1;32m    263[0m     [38;5;28;01myield[39;00m req
[1;32m    264[0m [38;5;28;01melse[39;00m:
[0;32m--> 266[0m     resp [38;5;241m=[39m [38;5;28mself[39m[38;5;241m.[39msend(
[1;32m    267[0m         req,
[1;32m    268[0m         stream[38;5;241m=[39mstream,
[1;32m    269[0m         timeout[38;5;241m=[39mtimeout,
[1;32m    270[0m         verify[38;5;241m=[39mverify,
[1;32m    271[0m         cert[38;5;241m=[39mcert,
[1;32m    272[0m         proxies[38;5;241m=[39mproxies,
[1;32m    273[0m         allow_redirects[38;5;241m=[39m[38;5;28;01mFalse[39;00m,
[1;32m    274[0m         [38;5;241m*[39m[38;5;241m*[39madapter_kwargs,
[1;32m    275[0m     )
[1;32m    277[0m     extract_cookies_to_jar([38;5;28mself[39m[38;5;241m.[39mcookies, prepared_request, resp[38;5;241m.[39mraw)
[1;32m    279[0m     [38;5;66;03m# extract redirect url, if any, for the next loop[39;00m

File [0;32m~/anaconda3/lib/python3.11/site-packages/requests/sessions.py:703[0m, in [0;36mSession.send[0;34m(self, request, **kwargs)[0m
[1;32m    700[0m start [38;5;241m=[39m preferred_clock()
[1;32m    702[0m [38;5;66;03m# Send the request[39;00m
[0;32m--> 703[0m r [38;5;241m=[39m adapter[38;5;241m.[39msend(request, [38;5;241m*[39m[38;5;241m*[39mkwargs)
[1;32m    705[0m [38;5;66;03m# Total elapsed time of the request (approximately)[39;00m
[1;32m    706[0m elapsed [38;5;241m=[39m preferred_clock() [38;5;241m-[39m start

File [0;32m~/anaconda3/lib/python3.11/site-packages/requests/adapters.py:532[0m, in [0;36mHTTPAdapter.send[0;34m(self, request, stream, timeout, verify, cert, proxies)[0m
[1;32m    530[0m     [38;5;28;01mraise[39;00m SSLError(e, request[38;5;241m=[39mrequest)
[1;32m    531[0m [38;5;28;01melif[39;00m [38;5;28misinstance[39m(e, ReadTimeoutError):
[0;32m--> 532[0m     [38;5;28;01mraise[39;00m ReadTimeout(e, request[38;5;241m=[39mrequest)
[1;32m    533[0m [38;5;28;01melif[39;00m [38;5;28misinstance[39m(e, _InvalidHeader):
[1;32m    534[0m     [38;5;28;01mraise[39;00m InvalidHeader(e, request[38;5;241m=[39mrequest)

[0;31mReadTimeout[0m: HTTPSConnectionPool(host='80.push2delay.eastmoney.com', port=443): Read timed out. (read timeout=15)

